repl: repl.c ../token.h ../scanner.h ../token.c ../scanner.c ../parser.c ../parser.h
	gcc -g -I.. -o $@ repl.c ../token.c ../scanner.c ../parser.c
tokens: tokens.c ../token.h ../scanner.h ../token.c ../scanner.c
	gcc -g -I.. -o $@ tokens.c ../token.c ../scanner.c
