repl: repl.c ../token.h ../scanner.h ../token.c ../scanner.c
	gcc -I.. -o $@ repl.c ../token.c ../scanner.c
tokens: tokens.c ../token.h ../scanner.h ../token.c ../scanner.c
	gcc -I.. -o $@ tokens.c ../token.c ../scanner.c
